# Generated by Django 5.0.4 on 2024-04-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=10)),
                ('item', models.CharField(max_length=10)),
                ('quanitity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pay_mode', models.CharField(max_length=10)),
            ],
        ),
    ]
